#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


last_remote_commit="$(git log --format="%H" -n 2 | tail -n 1)"
# check if remotes exist
if [ "$(git remote)" ]; then
    # a remote may exist but it might not have commits, so we will use the last local one
    last_remote_commit=$(git rev-parse origin/"$(git branch --show-current)") || "$last_remote_commit"
fi
last_local_commit=$(git log --format="%H" -n 1 | tail -n 1)
# detect force push, ref: https://github.com/kyanny/git-hooks-detect-force-update
if [ "$(git rev-list "$last_remote_commit" ^"$last_local_commit")" ]; then
    echo "Force push detected..."
    last_remote_commit="$last_local_commit"
fi
echo "Setting base=\"$last_remote_commit\" and head=\"$last_local_commit\""
for target in lint build; do
    pnpm nx affected \
        --base="$last_remote_commit" \
        --target="$target" \
        --nx-bail \
        --parallel=6
done

