name: Publish
on:
  push:
    branches:
      - main

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Prerelease Version
        run: npx nx affected --target=version --base=${{ github.event.before }} --head=HEAD --dry-run

  release:
    environment: production
    runs-on: ubuntu-latest
    needs: pre-release
    steps:
      - uses: actions/checkout@v3

      - name: Configure credentials
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}' > ~/.npmrc

      - name: Check npm credentials
        run: npm whoami

      - uses: ./.github/actions/setup

      - name: Configure github identify
        shell: bash
        run: |
          git config user.name "Github Actions"
          git config user.email "-"

      - name: Tag last-release
        run: git tag --force last-release

      - name: Version
        run: npx nx affected --target=version --base=${{ github.event.before }} --head=HEAD

      - name: Deploy
        run: npx nx affected --target=deploy --base=${{ github.event.before }} --head=HEAD

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true
