name: Publish
on:
  push:
    branches:
      - main

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup
        name: Setup environment

      - name: Set base commit hash
        run: |
          #!/usr/bin/env bash
          commit=${{ github.event.before }}
          if git branch --contains "$commit"; then
            echo "No force push detected, continuing..."
          else
            # get the commit before this one
            commit=$(git log --format="%H" -n 2 | tail -n 1)
          fi
          echo "BASE_COMMIT=$commit" >> $GITHUB_ENV

      - name: Display base commit
        run: echo "$BASE_COMMIT"

      - name: Prerelease Version
        run: pnpm nx affected --target=version --base=$BASE_COMMIT --head=HEAD --dry-run

      - name: Configure credentials
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}' > ~/.npmrc

      - name: Check npm credentials
        run: npm whoami

      - name: Configure github identify
        shell: bash
        run: |
          git config user.name "Github Actions"
          git config user.email "-"

      - name: Tag last-release
        run: git tag --force last-release

      - name: Build
        run: pnpm nx affected --target=build --base=$BASE_COMMIT --head=HEAD

      - name: Lint
        run: pnpm nx affected --target=lint --base=$BASE_COMMIT --head=HEAD

      - name: Version
        run: pnpm nx affected --target=version --base=$BASE_COMMIT --head=HEAD --parallel 1

      - name: Deploy
        run: ./deployment/publish.sh

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true
